eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    health-check-url-path: ${management.context-path}/health
    metadata-map:
      instance-id: test-sidecar
      management:
        context-path: ${management.context-path}
      user:
        name: test
        password: test
    prefer-ip-address: true
    status-page-url-path: ${management.context-path}/info
management:
  context-path: /admin
server:
  port: 3459
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, application/json, application/xml
sidecar:
  health-uri: ${sidecar.home-page-uri}/health
  home-page-uri: http://127.0.0.1:${sidecar.port}
  port: 8000
spring:
  application:
    name: test-sidecar
